### ISSUE TITLE
Typo https://github.com/Low-Drag-MC/Multiblocked/wiki/Tutorial:-Renderer

### ISSUE THREAD

**Issue by ZM-20-20** [Low-Drag-MC/Multiblocked#14]
https://github.com/Low-Drag-MC/Multiblocked/wiki/Tutorial:-Renderer

xxx.png file in the textuers folder("./multiblocked/assets/multiblocked/textuers"),

This should be 'textures'

**Comment by Yefancy** [comment]
fixed
