### ISSUE TITLE
使用生态群系检测时出现崩溃

### ISSUE THREAD

**Issue by MKMKLMLM** [Low-Drag-MC/Multiblocked#18]
游戏版本1.18.2
LowDragLib版本0.6.4
Multiblocked版本0.9.6
Forge版本40.1.60
没有安装opt，也没有安装其他任何mod
目前情况是只要是带有生态群系检测的合成表在生产时都会直接崩溃，看文件似乎和服务器有关，但测试时是单人游戏，崩溃报告：
[crash-2022-07-16_15.14.05-server.txt](https://github.com/Low-Drag-MC/Multiblocked/files/9125338/crash-2022-07-16_15.14.05-server.txt)

**Comment by Yefancy** [comment]
0.10.0修复
