### ISSUE TITLE
[1.16] Item output not outputting more than 1 item

### ISSUE THREAD

**Issue by AubriTheHuman** [Low-Drag-MC/Multiblocked#2]
When using an item output in a recipe, it won't output more than one item, even if set otherwise.

Also, the catalyst doesn't seem to matter, and the machine will form without it.

[Imgur of the output of the machine, working recipe, and the recipe in the blueprint table.](https://imgur.com/a/qf5yDSB)

[Pastebin for recipe json](https://pastebin.com/59ajcqXw)

[Pastebin for machine json](https://pastebin.com/v7MHJEK4)

**Comment by Yefancy** [comment]
540b6d1fd90521a923ba5b1930b15de679304a30 fixed
