### ISSUE TITLE
[1.18.2]生态群系检测失效

### ISSUE THREAD

**Issue by MKMKLMLM** [Low-Drag-MC/Multiblocked#21]
游戏版本1.18.2
Multiblocked 版本0.11.0
LDLib 版本0.7
forge 版本40.1.68
还是合成表生物群系条件检测的问题，最新版mod不会再崩溃了，但是似乎不能正常识别生态群系了
未安装其他mod，测试过40.1.0和40.1.50以上版本的forge，都是一样的情况
不知提供何种文件能帮助解决问题，见谅

**Comment by Yefancy** [comment]
已在0.11.1版本中修复
