### ISSUE TITLE
Geckolib multiblock render offset

### ISSUE THREAD

**Issue by Themporal** [Low-Drag-MC/Multiblocked#38]
I've been noticing a very small offset in where geckolib renders the multiblock over where it should be. I believe it's 0,2px too high.
![2022-10-21_20 18 04](https://user-images.githubusercontent.com/38329479/197264540-4d89354d-462a-4aa5-bf3b-11b65d82e4e5.png)
![Capture](https://user-images.githubusercontent.com/38329479/197264548-d3ad1e7f-2ca0-4e56-8852-54d13739bfb5.PNG)

**Comment by Yefancy** [comment]
https://github.com/bernie-g/geckolib/issues/307

**Comment by Yefancy** [comment]
You can fix it by adding a offset 0.16
