### ISSUE TITLE
关于槽位设置为IN后，物品可以放入但不能拿出的问题

### ISSUE THREAD

**Issue by StarZeroRI** [Low-Drag-MC/Multiblocked#40]
打个比方 有两个配方，

铁矿石->铁锭
铁锭->钢锭

这个左边槽位IN我只想放进铁矿石，然后右边槽位OUT输出铁锭（需要铁锭，不需要钢锭），如果槽位设置为BOTH，烧制完成后的铁锭还可能出现在左边槽位里面，就会导致继续工作，输出成钢锭了
![QQ图片20221022222559](https://user-images.githubusercontent.com/89684932/197344472-f2255393-9ea8-48c8-a3e6-1a712a72a651.png)
#
另一个问题就是如果设置成IN放进去的物品无法拿出来，如果是机器不需要的道具，就会一直卡着位置

**Comment by Yefancy** [comment]
新版还有个mbd io设置，你的需求应该这样设置：
左边GUI设置BOTH， CAP看你自己（是否用漏斗输入输出），MBD设置IN，添加铁矿石过滤
右边GUI设置OUT，CAP看你自己，MBD设置OUT
