### ISSUE TITLE
Not consumed output?

### ISSUE THREAD

**Issue by Themporal** [Low-Drag-MC/Multiblocked#41]
When creating a recipe and the output has a chance of 0 it says `not consumed` it would be better if it didn't show or said `not produced`.
![2022-10-27_09 50 33](https://user-images.githubusercontent.com/38329479/198223583-a139d2bb-cb96-4f6d-b456-8459a5a46797.png)

**Comment by Yefancy** [comment]
well, kind of weid to have an output which is impossible be produced
