### ISSUE TITLE
[Crash] [1.18] Crash when clicking in the menu with the latest version of JEI

### ISSUE THREAD

**Issue by Filostorm** [Low-Drag-MC/Multiblocked#42]
Multiblocked-1.18.2-0.12.3

LowDragLib-1.18.2-0.7.5

jei-1.18.2-forge-10.1.5.272

[crash-2022-10-28_21.35.00-client.txt](https://github.com/Low-Drag-MC/Multiblocked/files/9892621/crash-2022-10-28_21.35.00-client.txt)

**Comment by vfyjxf** [comment]
Please do not use Jei10, use Jei9, jei10 is not currently compatible.

**Comment by Filostorm** [comment]
Well, yes, I noticed. However, the newest version of AE requires the newest version of JEI, hence my report. 

I'm currently not using either of those so I can keep using multiblocked, but I assume that it's possible to fix.

**Comment by vfyjxf** [comment]
Yes, it's fixable, but then again that would crash player s using jei9, and for some reason it's harder to be compatible with both jei9 and jei10.

**Comment by Filostorm** [comment]
I see. It's not possible to have whatever's crashing check the version of JEI?

Either way it's not that difficult for current players to update JEI, so in my opinion it doesn't make sense to not make it compatible with the latest update. 

I suppose you could also label the update a beta so it doesn't show there's an update on the curse page when building a pack

**Comment by Filostorm** [comment]
Latest Update adds JEI 10 compat!
