### ISSUE TITLE
[1.18] Default Create parts not working as expected

### ISSUE THREAD

**Issue by Filostorm** [Low-Drag-MC/Multiblocked#45]
Input randomly breaks, seemingly from too much stress. Output does as well, but much more often.

Ideally it would be possible to speed up machine processing based on input speed as well.

**Comment by Yefancy** [comment]
I just find out reason that latest create will check frequency that machine updating, removing frequent ones. I just fix it.

Btw you'd better set a recipe with the duration longer than 10tick or it will still be broken
