### ISSUE TITLE
[1.18][Bug] Multiblocks with Create parts don't work on a restart

### ISSUE THREAD

**Issue by Filostorm** [Low-Drag-MC/Multiblocked#52]
You need to break and replace a block to reload the multi in order for it to work. If you break and replace the create part, it doesn't recognize the stress input, and you have to break and replace that as well. 

So for some reason the part has to be placed first.

**Comment by Yefancy** [comment]
I cant reproduce it. could you send me a vid or gif?

https://user-images.githubusercontent.com/18493855/204088201-871e64c2-597d-4bf7-bd5c-1e6336725df4.mp4

**Comment by Filostorm** [comment]
I'll do some more testing when I get a chance

**Comment by Filostorm** [comment]
also can't reproduce, closing

**Comment by Filostorm** [comment]
Welp, just had it happen. No clue why it did this time after working fine for a long time.
Unless the create update broke it.

**Comment by Filostorm** [comment]
Alright I'm just going to keep this closed till I can confirm the issue. Sorry about that

**Comment by Filostorm** [comment]
Break in the case, it seems like any multiblock sometimes can sometimes stop working, 

Before and after reforming. It seems like it stops knowing the parts are actually in/output.


![2023-02-06_05 39 23](https://user-images.githubusercontent.com/73716145/216950772-68019003-9310-4a58-bf3e-4adde8a19afb.png)
![2023-02-06_05 39 32](https://user-images.githubusercontent.com/73716145/216950767-04973b46-0372-44c0-ad47-e48e70b6b5c5.png)

**Comment by Yefancy** [comment]
it makes sense

**Comment by Filostorm** [comment]
I had several different multiblocks formed on the same world, all with the same problem. Nothing in the log that I could see

**Comment by Yefancy** [comment]
yeah, I have some clues

**Comment by Filostorm** [comment]
Seems to be fixed, all multiblocks work across world close/open now
