### ISSUE TITLE
[1.16-1.18] [功能请求] 与JEI相关的功能建议与疑问。

### ISSUE THREAD

**Issue by StarZeroRI** [Low-Drag-MC/Multiblocked#53]
功能建议：
1.在机器中点击“进度”则展示全部使用该机器的配方。
2.配方中的物品目前无法继续点击来查看合成方式。
疑问：
3.请问在JEI展示的多方块结构演示中，结构名字如何本地化（还是说出现了bug无法显示出来，结构名称、控制器名称、结构描述均可汉化）。

**Comment by Yefancy** [comment]
3. 不能复现，
