### ISSUE TITLE
[1.18] [Bug] Jei/Rei Issues

### ISSUE THREAD

**Issue by Filostorm** [Low-Drag-MC/Multiblocked#60]
When browsing recipes in a custom multiblock, there are a few issues. 

1) While hovering over the ingredient panel, you can't scroll through the recipe pages. I'm assuming this is to allow you to scroll if the ingredient list is longer then the box, but this shouldn't be an needed while we've got less then 9 inputs.

2) Left or right clicking (or using the hotkeys) on ingredients while the tooltip is shown does not navigate away from the page to the recipe/uses for the item. Notice I said while the tooltip is shown. It works as normal if you are at the very edge of the item.

3) Speaking of tooltips, the amount of items is shown through when hovering, as shown in the Red circle below.

![2023-01-30_06 40 02](https://user-images.githubusercontent.com/73716145/215467627-0f367519-4b8d-4e99-a01c-37c9248add11.png)

4) As shown in the Blue circle, recipe_map is misspelled as recupe_map

5) Slightly less important, the recipe name doesn't seem to be attached to the recipe in Jei/Rei, as you can see in the below two pictures, with the first being the MBD recipe and the second being a random other.

![2023-01-30_06 52 12](https://user-images.githubusercontent.com/73716145/215470147-c597729a-b6b3-4919-a2a6-2aae2b3e2f53.png)

![2023-01-30_06 52 27](https://user-images.githubusercontent.com/73716145/215470578-d648c572-813e-4747-93bc-f389ddc45f27.png)

6) Previews are still messed up, the first picture is when trying to view uses on the controller, the second is when viewing uses on one of the components of the multiblock. This issue only seems to pop up if you have ftb chunk loading and kubejs installed. This is a major issue imo, as these mods will be in most major modpacks that would use this mod.

![2023-01-30_06 50 42](https://user-images.githubusercontent.com/73716145/215471045-dd4d8739-3f54-47c3-8c59-0d074809a812.png)

![2023-01-30_06 50 30](https://user-images.githubusercontent.com/73716145/215471053-bb6696ed-1159-41cc-b549-cf10aaf145d9.png)

**Comment by vfyjxf** [comment]
Spelling errors are fixed in #59

**Comment by Filostorm** [comment]
Slight correction to 5, recipes don't have ids at all

**Comment by Filostorm** [comment]
Update to the rendering issue, it only seems to happen when you have recipes for the controller.
![2023-02-03_05 36 25](https://user-images.githubusercontent.com/73716145/216580298-418bd881-03d8-4f0b-8925-42193ebc0ec0.png)
![2023-02-03_05 36 27](https://user-images.githubusercontent.com/73716145/216580306-90fc5eaa-cc46-48af-b36a-6787493e2b9a.png)

**Comment by vfyjxf** [comment]
> Slight correction to 5, recipes don't have ids at all

Because mbd's recipe use it own's system,so rei/jei can't handle it.

**Comment by Yefancy** [comment]
> 

why cant rei/jei handle it

**Comment by vfyjxf** [comment]
> > 
> why cant rei/jei handle it

Because by default jei can only handle the RL returned by the getId method of the Recipe interface as an id, but mbd seems to only use the recipe type that implements the Recipe interface in the kubeJs compatible section(The MultiBlockRecipe), and the recipe created via the blueprint table is a separate Recipe whose id should be returned by IRecipeCategory(getRegistryName method), but mbd doesn't override this method either.

**Comment by Yefancy** [comment]
so that only if we implement `getID` will we address it?

**Comment by Yefancy** [comment]
3 + 6 are fixed

**Comment by Filostorm** [comment]
Update on "2. Left or right clicking (or using the hotkeys) on ingredients while the tooltip is shown does not navigate away from the page to the recipe/uses for the item. Notice I said while the tooltip is shown. It works as normal if you are at the very edge of the item."

You aren't able to use any mouse buttons, including scrolling and left/right click, and side buttons which were what I had my hotkeys bound to. Using regular keys as the hotkeys allows it to work fine.

**Comment by Filostorm** [comment]
I guess that's pretty much it for these issues!
