### ISSUE TITLE
Energy Hatch does not seem to send energy to controller

### ISSUE THREAD

**Issue by AFatFlyingWhale** [Low-Drag-MC/Multiblocked#73]
Either I'm doing something completely wrong, which is entirely possible, or the Energy Input hatch does not transfer energy to the multiblock, even if it is correctly given a slot, correctly configured, the recipe does not exceed input limitations, etc. It will accept energy, and hold it in its internal buffer, but not actually do anything with that energy. It is not an issue with the recipe, as it works both without an energy requirement and also with energy being piped directly into the controller.
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/1ffe9456-4491-4407-8b75-667f9259fa95)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/2dc1ee6a-da73-4dd2-b977-e58a9534f2d7)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/9902a5d8-35cf-4fd9-8c48-afde5af1b9f3)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/ca700e42-37d6-453a-874b-4f4017de06ac)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/f7e56bbf-6a01-4b86-95c1-edb7a2946d08)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/df67b792-578c-404b-ba15-cb68d8debed2)
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/16414417/882b8ac9-ad89-4d49-b2c0-1f19e0224a26)

**Comment by Gogo08190** [comment]
Same problem, work with Multiblocked-1.18.2-1.0.5 but doesn't work with Multiblocked-1.18.2-1.0.5.a / Multiblocked-1.18.2-1.0.6 and Multiblocked-1.18.2-1.0.7 !

**Comment by 321nick** [comment]
Im having a similar issue with Multiblocked-1.18.2-1.0.7, but i think FE usage is bugged regardless of input hatch or not. Even saving the multiblock as having no inventories and no FE buffers beyond the controller itself, aslong as theres an input of FE for the recipe it wont properly function. 

Here is my .json files(had to rename to .txt so i can upload):

This one for the multi block itself
[nick_driller_v3.txt](https://github.com/Low-Drag-MC/Multiblocked/files/11930356/nick_driller_v3.txt)

This one for the recipes:
[drillerv2_map.txt](https://github.com/Low-Drag-MC/Multiblocked/files/11930385/drillerv2_map.txt)

**Comment by Yefancy** [comment]
fixed in 1.0.7.a
