### ISSUE TITLE
1.18.2 Crash when clicking recipe button in JEI

### ISSUE THREAD

**Issue by 321nick** [Low-Drag-MC/Multiblocked#74]
when clicking the arrow here in the image (the one with the grey background), the game crashes. at first u can access this jei recipe previewer by clicking on the progress bar in the multiblocked UI. but then clicking on the arrow in the new UI (as seen in the image) crashes the game

The image:
![image](https://github.com/Low-Drag-MC/Multiblocked/assets/19196462/04300c22-3ff7-4605-ba88-5a9d707912fa)

Logs:
https://mclo.gs/ossAHns

**Comment by V2LenKagamine** [comment]
I can confirm this issue. I have attached a log of my personal Crash report.
[crash-2023-07-23_19.13.45-client.txt](https://github.com/Low-Drag-MC/Multiblocked/files/12140182/crash-2023-07-23_19.13.45-client.txt)

**Comment by Yefancy** [comment]
bump up ldlib to 1.0.8
