### ISSUE TITLE
[1.18.2] SP / SMP crash when trying access main table

### ISSUE THREAD

**Issue by ptk2003** [Low-Drag-MC/Multiblocked#75]
when right click on main table game crashed

forge-1.18.2-40.2.9
LowDragLib-1.18.2-1.0.7.a
Multiblocked-1.18.2-1.0.7.a (same in 1.0.7 and prev)
All other mod was temporary removed for test.
[crash-2023-07-04_10.18.47-client.txt](https://github.com/Low-Drag-MC/Multiblocked/files/11945945/crash-2023-07-04_10.18.47-client.txt)

**Comment by Yefancy** [comment]
install kjs. I accidentally relied on kjs
