### ISSUE TITLE
[1.18.2]服务器后台不断刷出 “controller capability proxies setting missmatching can't find a TileEntity at pos:...”信息导致无法操作

### ISSUE THREAD

**Issue by XBrilliantRain** [Low-Drag-MC/Multiblocked#77]
pos后的坐标为x=3320a z=3352b y=144（a，b为0-9任意数字）

**Comment by LeeJSwit-HCN** [comment]
<img width="520" alt="Cache_2ba40dbee0d6542b" src="https://github.com/Low-Drag-MC/Multiblocked/assets/62585835/728b101b-66e5-451f-999e-7b74dabb15eb">
就像这种情况？几乎是1秒弹出来一条。这是什么原因导致的？

**Comment by AnterCreeper** [comment]
同问

**Comment by LeeJSwit-HCN** [comment]
这个东西倒是不影响游戏，但是控制台看着很烦。
所以我加了这个mod：ConsoleSpamFix，用来消除这些warning

**Comment by Yefancy** [comment]
fixed in 1.0.9
