### ISSUE TITLE
Changing the default 500 RF in recipes breaks the recipe entirely

### ISSUE THREAD

**Issue by YahiaTGF** [Low-Drag-MC/Multiblocked#8]
When creating a recipe map, if you select '500 RF' option then change it to any other number causes the recipe to not work and for the multiblock to be stuck on idling.

The 'per tick' option seems to work as well as lowering the RF below the 500, changing it to more though doesn't seem to work.

**Comment by Yefancy** [comment]
fixed in the latest version
